name: Build, Scan, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:

env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: us-east-1
  S3BUCKET: my-codedeploy-artifacts-2      # update this bucket name
  S3bucket_CodeGuru: codeguru-reviewer-11   # update this bucket name

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0   # important for CodeGuru to see full Git history

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: chmod
        run: chmod -R +x ./.github

      - name: Build and Package Maven
        working-directory: ${{ env.applicationfolder }}
        run: $GITHUB_WORKSPACE/.github/scripts/build.sh

      - name: Upload Artifact to S3
        working-directory: ${{ env.applicationfolder }}/target
        run: aws s3 cp *.war s3://${{ env.S3BUCKET }}/

  codescan:
    name: CodeGuru Reviewer Scan
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      security-events: write
    steps:
      - name: Checkout Repository for CodeGuru
        uses: actions/checkout@v2
        with:
          fetch-depth: 0   # Full Git history required

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Run CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          s3_bucket: ${{ env.S3bucket_CodeGuru }}
          build_path: ./  # root folder with .git

      - name: Store SARIF file
        uses: actions/upload-artifact@v4
        with:
          name: SARIF_recommendations
          path: ./codeguru-results.sarif.json

      - name: Upload Review Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-results.sarif.json

      - name: Fail on Critical Vulnerabilities
        run: |
          echo "Checking for critical vulnerabilities..."
          count=$(jq '.runs[].results[] | select(.level == "error") | .level' codeguru-results.sarif.json | wc -l)
          if (( $count > 0 )); then
            echo "There are $count critical findings, stopping the pipeline."
            exit 1
          fi

  deploy:
    name: Deploy to EC2
    needs: codescan
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Application
        run: |
          echo "Deploying branch ${{ github.ref }} to environment: Dev"
          commit_hash=$(git rev-parse HEAD)
          aws deploy create-deployment \
            --application-name MyWebApp \
            --deployment-group-name MyWebAppDG \
            --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash \
            --ignore-application-stop-failures
